[versions]
# libraries
junit = "5.13.4"
opentest4j = "1.3.0"
mockk = "1.14.5"
systemLambda = "1.2.1"

appdirs = "1.4.0"
commonsCompress = "1.27.1"

# plugins
changelog = "2.3.0"
intelliJPlatform = "2.5.0"
kotlin = "2.2.0"
kover = "0.9.1"
qodana = "2025.1.1"

[libraries]
junitVintageEngine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
jupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
appdirs = { group = "net.harawata", name = "appdirs", version.ref = "appdirs" }
commonsCompress = { group = 'org.apache.commons', name = 'commons-compress', version.ref = 'commonsCompress' }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
systemLambda = { group = "com.github.stefanbirkner", name = "system-lambda", version.ref = "systemLambda" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
